name: minitranslate
description: HW3


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter




  cupertino_icons: ^1.0.0
  pedantic: ^1.0.0
  audioplayers: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  assets:
    - assets/eu.mp3
    - assets/ich.mp3

  uses-material-design: true


